blueprint: file

title: Image

accept:
  type: image
  extension: jpg, png, jpeg
  mime: image/jpeg, image/png


  fields:
    title:
      label: Titre
      type: text
      width: 2/3
    credit:
      label: Crédits
      type: text
      width: 2/3
