blueprint: site

options:
  changeTitle: true
  preview: https://fashionnarratives.ch

columns:
  - width: 1/4
    sections:
      projects:
        label: " "
        type: pages
        status: listed
        image:
          cover: false
          back: white
        templates: site-details
        layout: cards
        size: medium
  - width: 1/4
    sections:
      about:
        label: " "
        type: pages
        status: listed
        image:
          cover: false
          back: white
        templates: glossary
        layout: cards
        size: medium
  - width: 1/4
    sections:
      themeList:
        label: " "
        type: pages
#        status: listed
        image:
          cover: false
          back: white
        templates: scenarios
        layout: cards
        size: medium
